### ISSUE TITLE
Two more unlisted shortcuts: \sin and \cos

### ISSUE THREAD

**Issue by Cliff122** [Notuom/google-docs-equation-shortcuts#1]
I recently found out about two new, unlisted shortcuts by accident. They are `\sin` and `\cos`.

Both basically just write out the function name, but without cursive and as one character. They also have better spacing then when written out with just letters.

Thought it could be useful to add them to the cheatsheet though, to make it more complete.

**Comment by Notuom** [comment]
Thanks @Cliff122, I'll add those to the unlisted section!
