### ISSUE TITLE
Lots of math characters under Insert/Special Character

### ISSUE THREAD

**Issue by AxelBoldt** [Notuom/google-docs-equation-shortcuts#10]
While not directly a part of the equation editor, there are lots of useful math characters to be found under Insert/Special Character in the categories Symbol/Arrows, Symbol/Math and Symbol/Math alphanumeric.

**Comment by Notuom** [comment]
That's true, I remember using that feature a lot when I was using Google Docs a lot. I've added the tip in the introduction. Thanks!
