### ISSUE TITLE
\nabla ∇ 

### ISSUE THREAD

**Issue by felixilie** [Notuom/google-docs-equation-shortcuts#12]
Great list!
Please add the \nabla ∇  sign (reverse delta) to the Miscellaneous operations.
Thank you.

**Comment by Notuom** [comment]
Thanks for the suggestion! It's already been added in the "unlisted" section under "symbols" as requested in #6: 
https://www.notuom.com/google-docs-equation-shortcuts.html#unlisted

I'm open to suggestions if there's a way to make it easier to find :slightly_smiling_face:

**Comment by felixilie** [comment]
So true! I would maybe just add the sign ∇ to the description to make it more visible.
Thanks again!

**Comment by Notuom** [comment]
Good idea!
