### ISSUE TITLE
Add \hat to the list

### ISSUE THREAD

**Issue by maxpatiiuk** [Notuom/google-docs-equation-shortcuts#16]
`\widehat` is already present, so `\hat` should be added to

**Comment by Notuom** [comment]
Thanks for the suggestion!

This was already added earlier in #3 under the [unlisted section](https://equation-shortcuts.notuom.com/#unlisted) since it's not in the equation menu. I added images to the unlisted section today so hopefully it makes it easier to find and visualize those.
