### ISSUE TITLE
Add \limsup, \liminf to Unlisted Operations and \lg, \gcd, \sup, \inf, \arg, \deg, \det, \dim, \hom, \ker, \Pr to Unlisted Keywords

### ISSUE THREAD

**Issue by NovaFlint** [Notuom/google-docs-equation-shortcuts#19]
I found \sup, \inf, \deg just messing around, and got the rest from [Wikipedia's List of mathematical abbreviations](https://en.wikipedia.org/wiki/List_of_mathematical_abbreviations). I only tried most of them, so there could be a few I missed.

**Comment by Notuom** [comment]
Thank you! I added all of those along with more in the latest update.
