### ISSUE TITLE
Missing commands

### ISSUE THREAD

**Issue by vincent-silva** [Notuom/google-docs-equation-shortcuts#20]
Inspecting the code I found that there are 188 different commands, here are a list of the ones what I think are missing.
tanh
inf
mina
lg
binomab
limsupa
dim
ddot
dot
Pr
maxa
parallel
cosh
hom
sup
hbar
lima
sinh
propto
arg
underline
vdots
deg
cdots
gcd
liminfa
det
ker
liminfab
limsupab
ldots
coth

**Comment by Notuom** [comment]
Thanks for the exhaustive list! I tested each of them out and added them in the appropriate section along with an illustration of the result where necessary.
