### ISSUE TITLE
\lim different from \limab

### ISSUE THREAD

**Issue by MysticalMayhem** [Notuom/google-docs-equation-shortcuts#26]
The list of Shortcuts presents \lim and \limab as interchangeable, but it should be \lim and \lima instead.
<img width="208" alt="image" src="https://user-images.githubusercontent.com/65586292/205971253-20422466-5f1c-4362-b955-5ad00212261b.png">
<img width="526" alt="image" src="https://user-images.githubusercontent.com/65586292/205971668-31415149-a988-45d4-9d21-cf895b3b741b.png">
<img width="493" alt="image" src="https://user-images.githubusercontent.com/65586292/205971934-56ca24da-f38e-4aed-a03b-197e4c123186.png">

**Comment by Notuom** [comment]
Thanks for the catch!
