### ISSUE TITLE
new command \vec

### ISSUE THREAD

**Issue by seanwbarry** [Notuom/google-docs-equation-shortcuts#4]
\vec works and isn't currently listed

**Comment by Notuom** [comment]
Thanks @seanwbarry, I'll add it to the unlisted section!

**Comment by PeterOdogwu** [comment]
Any way to get the reverse vector symbol?

**Comment by Notuom** [comment]
@PeterOdogwu You can do `\leftarrow` but unfortunately I don't know of a way to put it on top of another symbol like with `\vec`.
