### ISSUE TITLE
More unlisted trigonometric functions: \tan, \arcsin, \arccos and \arctan

### ISSUE THREAD

**Issue by Cliff122** [Notuom/google-docs-equation-shortcuts#5]
Found even more unlisted trigonometric functions today, in addition to the ones already on the list. They are: `\tan`, `\arcsin`, `\arccos` and `\arctan`.

All of these follow the same format, just the name of the function, but with better spacing and without cursive.

**Comment by Notuom** [comment]
Thanks!
