### ISSUE TITLE
Replace \intab with \int

### ISSUE THREAD

**Issue by maxpatiiuk** [Notuom/google-docs-equation-shortcuts#7]
The following shortcuts produce the same result:
`\intab` and `\int`
`\ointab` and `\oint`
`\sumab` and `\sum`
`\limab` and `\lim`

Replacing longer versions with shorter variants may make them be easier to remember

**Comment by Notuom** [comment]
Thanks! I've renamed the main functions and kept the longer versions too as alternatives.
